"""
Set up data infrastructure for hybrid approach.
Creates directories and prepares everything for:
- Your 800 recordings (tomorrow)
- TTS samples (now)
- Common Voice samples (optional)
"""

import os
import argparse
from pathlib import Path

def setup_directories(base_dir: str = "data"):
    """Create directory structure for hybrid data approach."""
    print("=" * 70)
    print("SETTING UP DATA INFRASTRUCTURE")
    print("=" * 70)
    
    directories = [
        f"{base_dir}/raw/user_recorded",      # Your 800 recordings (tomorrow)
        f"{base_dir}/raw/tts_generated",      # TTS samples (now)
        f"{base_dir}/raw/commonvoice",        # Common Voice (optional)
        f"{base_dir}/manifests",              # CSV files
    ]
    
    print(f"\n📁 Creating directories...")
    for dir_path in directories:
        os.makedirs(dir_path, exist_ok=True)
        print(f"   ✅ {dir_path}")
    
    # Create .gitkeep files to preserve empty directories
    for dir_path in directories:
        gitkeep = os.path.join(dir_path, ".gitkeep")
        if not os.path.exists(gitkeep):
            Path(gitkeep).touch()
    
    print(f"\n✅ Directory structure ready!")
    return directories

def create_data_readme(base_dir: str = "data"):
    """Create README explaining data organization."""
    readme_path = os.path.join(base_dir, "README.md")
    
    content = """# Data Organization

This directory contains all training data organized by source.

## Directory Structure

```
data/
├── raw/
│   ├── user_recorded/      # Your 800 manual recordings (add tomorrow)
│   ├── tts_generated/       # TTS-generated samples (generated now)
│   └── commonvoice/         # Common Voice samples (optional)
└── manifests/
    ├── train.csv            # Training manifest
    └── val.csv             # Validation manifest
```

## Data Sources

### 1. User Recorded (800 samples - add tomorrow)
- Your manual recordings
- Place files in: `data/raw/user_recorded/`
- Update: `data/manifests/train.csv` with paths

### 2. TTS Generated (200-300 samples - generated now)
- Text-to-Speech generated samples
- Generated by: `python scripts/generate_tts_samples.py`
- Saved to: `data/raw/tts_generated/`

### 3. Common Voice (500 samples - optional)
- Common Voice dataset samples
- Integrated by: `python scripts/integrate_commonvoice.py`
- Saved to: `data/raw/commonvoice/`

## CSV Format

Both `train.csv` and `val.csv` use the same format:
```csv
path,text
raw/user_recorded/sample_001.wav,hello how are you
raw/tts_generated/tts_0001.wav,this is a test
```

## Next Steps

1. ✅ TTS samples generated (done now)
2. ⏳ Add your 800 recordings (tomorrow)
3. ⏳ Optional: Add Common Voice samples
4. ⏳ Run: `python check_data_quality.py`
5. ⏳ Run: `python run_all.py` to train
"""
    
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\n📝 Created README: {readme_path}")

def main():
    parser = argparse.ArgumentParser(description='Set up data infrastructure')
    parser.add_argument('--base_dir', type=str, default='data',
                       help='Base directory for data')
    
    args = parser.parse_args()
    
    # Setup directories
    directories = setup_directories(args.base_dir)
    
    # Create README
    create_data_readme(args.base_dir)
    
    print("\n" + "=" * 70)
    print("✅ DATA INFRASTRUCTURE READY")
    print("=" * 70)
    print(f"\n📋 Next steps:")
    print(f"1. Generate TTS samples:")
    print(f"   python scripts/generate_tts_samples.py --num_samples 200")
    print(f"\n2. Tomorrow: Add your 800 recordings to:")
    print(f"   {args.base_dir}/raw/user_recorded/")
    print(f"   (Update train.csv with paths)")
    print(f"\n3. Optional: Add Common Voice samples")
    print(f"   python scripts/integrate_commonvoice.py --instructions")
    print(f"\n4. Check data quality:")
    print(f"   python check_data_quality.py")
    print(f"\n5. Train model:")
    print(f"   python run_all.py")

if __name__ == "__main__":
    main()

